version: '3'

services:
  nginx-static:
    image: nginx:latest
    ports:
      - "443:443"
    container_name: nginx-static
    volumes:
      - ./nginx-static/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - /etc/letsencrypt/live:/etc/letsencrypt/live # current certificate
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive # all certificates (symlinks from /live points here)
    depends_on:
        - backend

  backend:
    build: './backend'
    command: 'npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
      - /usr/app/tmp
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
