version: '3'

services:
  nginx-dev:
    image: nginx:latest
    ports:
      - "443:443"
    container_name: nginx-dev
    volumes:
      - ./nginx-dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-dev/certs/server.crt:/etc/nginx/certs/server.crt
      - ./nginx-dev/certs/server.key:/etc/nginx/certs/server.key
      - ./static:/var/www/static
    depends_on:
        - backend
        - frontend

  backend:
    build: './backend'
    command: 'npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
      - /usr/app/tmp
    depends_on:
      - database

  frontend:
    build: './frontend'
    command: 'npm start'
    ports:
      - '4200:4200'
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules

  database:
    image: mongo:latest
    command: mongod --port 27429
    environment:
      - MONGO_INITDB_ROOT_USERNAME=application
      - MONGO_INITB_ROOT_PASSWORD=changeme42